### ISSUE TITLE
UWP sample or UWP SDK is missing

### ISSUE THREAD

**Issue by ArchieCoder** [microsoft/immersive-reader-sdk#108]
In the provided samples for the Immersive Reader, only iOS has a SDK. It would be nice if UWP gets some love here.

Thanks

**Comment by dpaulino** [comment]
I am wondering the same thing. Would love to use this for Windows.

**Comment by ArchieCoder** [comment]
Until there is an official SDK, I found a way: 

1- Embed the immersive.txt file in your UWP app
2- Retrieve a token at runtime
3- Replace all the fields mark as "| |" with proper values
4- Call WebClient.NavigateString(immersiveContent)

[immersive.txt](https://github.com/microsoft/immersive-reader-sdk/files/4013185/immersive.txt)

**Comment by dpaulino** [comment]
Fantastic, thank you! I'm going to try this out!

**Comment by dpaulino** [comment]
Created a pull request to add an ImmersiveReaderView control for uwp apps #164. Sample app is included as well. Thanks @ArchieCoder for showing how to get it running in the first place!
