### ISSUE TITLE
gotOS() returns undefined on iOS 12 and earlier with overridden user-agent

### ISSUE THREAD

**Issue by FilipWennerdahl** [microsoft/immersive-reader-sdk#132]
Just like mentioned in #86 in a comment from @robinwassen, the getOS() function returns undefined when using a custom user-agent.
![Screenshot 2019-12-05 at 08 49 18](https://user-images.githubusercontent.com/23334491/70215586-12db6200-173e-11ea-96c6-e15434b158b3.png)

It was fixed for iOS 13 but it still does not work on iOS 12 and earlier.

**Comment by dylankil** [comment]
@FilipWennerdahl Hello, Filip. If you would please test the 1.1.0 SDK, there's a recently merged change in the Immersive Reader web application that should fix this null reference exception. Let us know if this issue has been resolved.
