### ISSUE TITLE
Unauthorized 

### ISSUE THREAD

**Issue by kyo3rar** [Microsoft/immersive-reader-sdk#14]
I'm trying to run a sample 
but it always returns
message: "Unauthorized"
in this request  
"
Request URL: https://learningtools.onenote.com/learningtoolsapi/cognitive/v2.0/GetContentModelForReader
Request Method: POST
Status Code: 401 

Accept: application/json, text/javascript, */*; q=0.01
Authorization: CogSvcsAccessToken {Token}
Content-Type: application/json
MS-Int-AppId: Cognitive
"

**Comment by metanMSFT** [comment]
Hi there, do you have an Immersive Reader subscription?

**Comment by kyo3rar** [comment]
I use Cognitive Services  subscription

I can't find Immersive Reader subscription in Services  ???

**Comment by kyo3rar** [comment]
who I can get Immersive Reader subscription?

**Comment by metanMSFT** [comment]
Apologies! The Immersive Reader is currently not yet publicly available, and at this time, I unfortunately cannot disclose when it will become available. Sorry for the inconvenience. Please check back often :)
