### ISSUE TITLE
Overlay doesnt close on route change

### ISSUE THREAD

**Issue by didair** [microsoft/immersive-reader-sdk#185]
Hi,

we use Immersive Reader on a few places in our project with React and React router. Theres a confusing behaviour of the Immersive Reader overlay. If the user goes back a page etc with the browser controls the Immersive Reader overlay is still showing. Can I fix this? Is this expected behaviour on your end?

**Comment by dylankil** [comment]
You may be able to fix this by calling the [close()](https://docs.microsoft.com/en-us/azure/cognitive-services/immersive-reader/reference#close) function on any route change where the current route isn't the one that the Immersive Reader should be open.

**Comment by didair** [comment]
Yes that worked! I couldnt find the reference anywhere, so Im going to create a PR to add it in the readme.
