### ISSUE TITLE
onPreferencesChanged does not support shouldTranslateDocument

### ISSUE THREAD

**Issue by cadi3s** [microsoft/immersive-reader-sdk#194]
Hi, if a user selects 'translate document', I want to remember that setting and lauch each new instance of ImmersiveReader with autoEnableDocumentTranslation = true until the user switches this off again.

Unfortunately, the onPreferencesChanged callback is not called when changing the 'translate document' button.
And if the onPreferencesChanged callback is called for something else, the translationState does not contain a flag for e.g. shouldTranslateDocument.

Is this a bug, and if so, is a fix on the roadmap?

Tested with immersive-reader-sdk.js version 1.1.0.

**Comment by dylankil** [comment]
Hello, @cadi3s 

A fix was merged into the private Immersive Reader repo on AzureDevOps on 08/27 that should resolve this issue, but has yet to be deployed. As soon as it's deployed I'll reply to this conversation

**Comment by dylankil** [comment]
The change has been deployed. Please test at your earliest convenience.

**Comment by cadi3s** [comment]
Sorry not seeing the change.. deployed where?  In the master I see only the renderButtons fix from a week ago, no other updates or merges since v1.1.0 in august.

**Comment by dylankil** [comment]
Not an SDK fix. Some changes to the Immersive Reader web application were deployed fixing numerous issues regarding user prefs as passing translation options should indeed change the preferences string. Though I may have misunderstood as there were bugs related to shouldTranslateWords in addition to your concern. I'll create a task to include ShouldTranslateDocument in the user preferences of the web application too as it's currenly not included in the user preferences string. This change will be deployed to the Immersive Reader web application - I'll ping again asap.

**Comment by dylankil** [comment]
We've logged a bug internally, closing.
