### ISSUE TITLE
Add option to turn off Grammar and Translation buttons

### ISSUE THREAD

**Issue by cadi3s** [microsoft/immersive-reader-sdk#195]
In a Learning Management System, some courses are about learning a different language.
In such cases reading an assignment in the original language with ImmersiveReader can be very helpful, but a teacher would not want their students to see the correct translation.

**Comment by tylerthedeveloper** [comment]
@cadi3s do you envision passing options such as "disableGrammar" and or "disableTranslation" booleans ?

**Comment by cadi3s** [comment]
Yes please!

**Comment by tylerthedeveloper** [comment]
Ack - i am now tracking this internally.

Please note this is considered an enhancement so we dont have a timeline for it yet and will prioritize based on customer need
