### ISSUE TITLE
Need a "Stop" or "Pause"\"Resume" API from IR team. Without this, we can't pause or resume audio talkback.

### ISSUE THREAD

**Issue by vbhatnagms** [microsoft/immersive-reader-sdk#199]
Scenario : Voiceover Audio does not stop even when we go away from the Android app(using IR web sdk)
Repro Steps
--------------
Install App  
launch app 
capture/select any image which has text.
Done
open immersive reader in save targets screen
play audio
Press Home button and switch to a different app.

Expected
-----------
Voiceover Audio should stop.

Actual.:
Audio did not stop if we go to different app

**Comment by dylankil** [comment]
Added to the [0.5.x-master](https://github.com/microsoft/immersive-reader-sdk/blob/0.5.x-master/js/src/launchAsync.ts) internal SDK.
