### ISSUE TITLE
Browser default language - translation function does not work

### ISSUE THREAD

**Issue by AngusLu** [microsoft/immersive-reader-sdk#211]
When the browser default language is Chinese, the translation function cannot translate English to Chinese. Cases that cannot be translated:
(1) When the browser default language is Chinese, the text content is "How are you", and then choose to translate into Chinese.
(2) When the browser default language is English, the text content is "你好嗎", and then choose to translate into English.

SDK version: 1.1.0
Browser version: Chrome 86.0.4240.198

**Comment by dylankil** [comment]
We've logged a bug internally, closing.
