### ISSUE TITLE
What is the latest npm version

### ISSUE THREAD

**Issue by adrienpoly** [microsoft/immersive-reader-sdk#216]
Hello the latest version on Github is 1.1.0 but on npm a `yarn add @microsoft/immersive-reader-sdk` adds version 0.5.2 that was released few days ago.

I am confused with those recent versions

source : https://www.npmjs.com/package/@microsoft/immersive-reader-sdk?activeTab=readme

**Comment by dylankil** [comment]
Hello, @adrienpoly. Sorry for the confusion! We've a few internal versions that are periodically updated. The latest nom is v1.1.0.

**Comment by adrienpoly** [comment]
Thanks currently anyone doing yarn add is getting  0.5.2. 

The temp solution is to do yarn add `yarn add @microsoft/immersive-reader-sdk@1.1.0`

I ll let you close this issue once it is resolved as for me it remains a problem to solve 

thanks
