### ISSUE TITLE
Doesn't work correctly

### ISSUE THREAD

**Issue by ricardosinchiguano1995** [microsoft/immersive-reader-sdk#22]
I can't see the immersive reader. Only this message."The appropriate information could not be obtained to display the text correctly."

**Comment by metanMSFT** [comment]
Hi, the Immersive Reader is currently in private preview. Are you a private preview partner?

**Comment by ricardosinchiguano1995** [comment]
Hi dear friend, tanks for your help. Actually we ar microsoft gold partner in Ecuador and we have development competition. We are interesting to register in preview partner to use immersive reader. Can you help us  to register in preview partner?

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by ricardosinchiguano1995** [comment]
> 
> 
> Hi, the Immersive Reader is currently in private preview. Are you a private preview partner?

Hi friend, thanks for you help. 
Actually we are microsoft gold partner in Ecuador and we have development competition. We are ineteresting to register in preview partner to use immersive reader. . Can you hel us to register in preview partner?.What is your mail to talk directly?

**Comment by metanMSFT** [comment]
Hi, you can send me an email at metan [at] microsoft.com. Thanks!
