### ISSUE TITLE
Microsoft branding should be hidden in Microsoft apps 

### ISSUE THREAD

**Issue by dylankil** [microsoft/immersive-reader-sdk#243]
![1st Party Logo](https://user-images.githubusercontent.com/22917282/108406952-f0fdbc00-71d7-11eb-9795-cf908af91cf8.png)

Some Microsoft applications use the Immersive Reader SDK, there's no need to show the logo in these apps.

**Comment by tylerthedeveloper** [comment]
@dylankil can we close this? I can grab the old PR for it
