### ISSUE TITLE
Let user override styles of the iframe container. [Internal SDK v.0.5.5]

### ISSUE THREAD

**Issue by franciscojgtz** [microsoft/immersive-reader-sdk#256]
The iframe container currently has a `position: relative`. This causes an issue when the iframe container is appended to a parent element other than the document's body. I would suggest letting the consumer of the SDK override the styles of the iframe container.

**Comment by tylerthedeveloper** [comment]
@franciscojgtz out of curiosity can you share sample sample overrides you'd like to add?
This would help during testing as we may initially restrict what props / attributes we accept
It would be hard to sign off on blanketly taking in styles and appending them to start

**Comment by tylerthedeveloper** [comment]
This will be included in next internal release.
