### ISSUE TITLE
Can't reopen Immersive Reader without refreshing if user exits early

### ISSUE THREAD

**Issue by livcheerful** [microsoft/immersive-reader-sdk#257]
We just added Immersive Reader to the [MakeCode Arcade tutorials](https://arcade.makecode.com/), and we've noticed that if an error occurs between launching the Immersive Reader and displaying the content, and the user presses the back button, they won't be able to reopen it until they refresh (with an '**Immersive Reader is already launching**' error). 

For example, if a user loses internet connection while launching, they won't be able to launch again.

I did a local build of the SDK where I added `isLoading = false ` to the exit function -- https://github.com/microsoft/immersive-reader-sdk/blob/60aaec313841ee2bc79875c09ba557e34f2469ab/js/src/launchAsync.ts#L134, and it seems to fix it for our case! But let me know if we're calling the SDK incorrectly and this isn't a bug 😊 I am also happy to open a PR to contribute!

**Comment by dylankil** [comment]
@livcheerful Please do open a PR and target the dev branch!

**Comment by livcheerful** [comment]
I put up a PR at https://github.com/microsoft/immersive-reader-sdk/pull/262 !

**Comment by tylerthedeveloper** [comment]
Closing as the PR was merged
