### ISSUE TITLE
Play/pause button trails offscreen in iOS Safari

### ISSUE THREAD

**Issue by livcheerful** [microsoft/immersive-reader-sdk#280]
When using iOS Safari, the Play/Pause button get pushed offscreen when there are multiple tabs open.

with tabs:
![image](https://user-images.githubusercontent.com/18712271/123136600-f67a4580-d407-11eb-8526-1a4c731ba118.png)

without tabs:
![image](https://user-images.githubusercontent.com/18712271/123136653-085be880-d408-11eb-8e92-9315c82b8658.png)

**Comment by dylankil** [comment]
We've logged a bug internally, closing.
