### ISSUE TITLE
Break/pause between line

### ISSUE THREAD

**Issue by Hantse** [microsoft/immersive-reader-sdk#281]
Hello, 
In "old" documentation, i think i read i'ts possible to add some html mark to break/pause the reader ? Actually, i don't find way to stop reader after each line. 

Kind regards,

**Comment by dylankil** [comment]
Hello, @Hantse 

The Immersive Reader doesn't support pausing text-to-speech at the end of each line. Unfortunately, this probably isn't going to make the feature backlog.
