### ISSUE TITLE
Unable to create Immersive Reader with AAD configuration according to PowerShell script

### ISSUE THREAD

**Issue by thomasgauvin** [microsoft/immersive-reader-sdk#348]
This resource https://docs.microsoft.com/en-us/azure/applied-ai-services/immersive-reader/how-to-create-immersive-reader documents a PowerShell script that would create the resources and configure them as need be. However, I am encountering troubles trying to execute the script, such as the following:

```
SecretExpiration '2022-12-31'                        
Exception: 
Line |
  17 |          throw "Error: AADAppIdentifierUri must be a valid URI"
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Error: AADAppIdentifierUri must be a valid URI
```

![image](https://user-images.githubusercontent.com/35609369/155785522-cbf417dc-2988-490d-9a3e-3af94ecd51fe.png)

Is there any advice or fix for this?

**Comment by rwallerms** [comment]
Hi @thomasgauvin, what value are you passing in for the AADAppIdentifierUri parameter?

The value needs to be a Absolute URI with the https scheme prefix, like below:
`https://immersivereaderaad-mycompany`

The script is calling Uri.TryCreate() for with UriKind.Absolute, as described here:
https://docs.microsoft.com/en-us/dotnet/api/system.uri.trycreate?view=net-6.0

**Comment by thomasgauvin** [comment]
Hi @rwallerms, this is indeed the value that I was passing. I have an ongoing support request and will document the conclusion form that. Thank you for your response.

**Comment by rwallerms** [comment]
@thomasgauvin, found this related issue. It suggests there was an AAD breaking change recently and perhaps upgrading PowerShell Az.Resources module will help.

https://github.com/Azure/azure-powershell/issues/16097#:~:text=Context,AzADServicePrincipal%20or%20New%2DAzADApplication%60.


Here was the notice of the AAD breaking change, which was posted in the thread above

https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-breaking-changes#appid-uri-in-single-tenant-applications-will-require-use-of-default-scheme-or-verified-domains

**Comment by rwallerms** [comment]
Determined the fix with @thomasgauvin, which was to use the `api://` scheme prefix, instead of `https://`, on the AAD URI. Thanks again for your help Thomas!

How To Doc has been updated with this info.

https://docs.microsoft.com/azure/applied-ai-services/immersive-reader/how-to-create-immersive-reader
