### ISSUE TITLE
why there is no immersive reader in linux? at least make it SaaS

### ISSUE THREAD

**Issue by rizkidotme** [microsoft/immersive-reader-sdk#465]
hey there i really love immersive reader when i was using Windows. it is amazing. it just perfect. but now i am using Linux due to system performance issue. i have Azure Account and why don't just charge me when i want use Immersive Reader in linux using AAD auth. i am really dissapointed by this decision. this technology should accessible to anyone, even for people "tech savvy" because not all people have time to build their own Immersive Reader. i try to build Chromium Extentions using microsoft account log in. i wish i can find a way to make this tech more accessible to many people. please help me.

**Comment by cristobal-buenrostro** [comment]
Thank you for your input, closing this issue for now. We are taking it under future consideration and opening a work item. We will follow it up later based on our backlog prioritization.
