### ISSUE TITLE
Python documentation

### ISSUE THREAD

**Issue by r3dh0t** [microsoft/immersive-reader-sdk#48]
Can you please add python documentation for Immersive Reader, specifically a Flask example would be very helpful.

**Comment by metanMSFT** [comment]
Hi @r3dh0t, we have a Python sample here: https://github.com/microsoft/immersive-reader-sdk/tree/master/samples/advanced-python.

**Comment by irlcaf** [comment]
Hey @metanMSFT where can I find the advanced-python sample?
