### ISSUE TITLE
Change Voice Engine || Open Source Immersive Reaader?

### ISSUE THREAD

**Issue by jeremiahoclark** [microsoft/immersive-reader-sdk#484]
Hi there, 
Love the project. I would like to request to enable OpenAI's TTS for the voice instead of MSFT's model. Ideally, the voice method would take an openAI key parameter and then allow the developer to use that model and the voice options within. 

I'm not sure how much support Immersive Reader is getting right now but if you open-source it then it may take off as engineers are working with text AI more than ever before. 

Cheers, 
Jeremiah

**Comment by cristobal-buenrostro** [comment]
Thank you for your input, closing this issue for now. We are taking it under future consideration and opening a work item. We will follow it up later based on our backlog prioritization.
