### ISSUE TITLE
Chrome app compatibility mode loads blank iframe

### ISSUE THREAD

**Issue by robinwassen** [microsoft/immersive-reader-sdk#49]
We have immersive-reader into our app which is running as a Chrome app, as mentioned in #8 we are launching with the option useWebview: true. But end up with a blank iframe inside the WebView (from a user perspective the app becomes white).

**Code used to launch Immersive Reader:**

```
const content = {
    title: self.question.title,
    chunks: [ {
        content: helperElement.innerText,
    } ],
};

const options = {
    useWebview: true,
}

ImmersiveReader.launchAsync(accessToken, content, options);
```

**Result:**
![image](https://user-images.githubusercontent.com/302151/60423435-82c54980-9bee-11e9-8060-91074de9e5c5.png)

In our Electron app immersive reader works with `useWebview: false`, if `useWebview: true` is set in the Electron app it produces the exact same result. 

I know that useWebview option is designed for Chrome though.

**Comment by metanMSFT** [comment]
This has been fixed in the Immersive Reader app. You will not need to update the SDK to get the fix.

**Comment by robinwassen** [comment]
Thank you for the quick response @metanMSFT. 

Tested our app and it works as intended now.
