### ISSUE TITLE
Add option to paginate content

### ISSUE THREAD

**Issue by jeremiahoclark** [microsoft/immersive-reader-sdk#495]
Azure Services charges by the character, so it would be nice to allow developers to throttle characters through pagination. It is quite easy to implement and would enhance the user experience by organizing content into structured pages. It would also enhance the developer experience, so developers and allow users to have predictable costs. This is not available as a feature in the Immersive Reader at this time.

Alternatively, and I've mentioned this before, perhaps consider open sourcing Immersive Reader. Immersive Reader is a great product with tons of unrealized potential. Open sourcing would be great PR for MSFT & IR and accelerate this product.

**Comment by cristobal-buenrostro** [comment]
Thank you for your input, closing this issue for now. We are taking it under future consideration and opening a work item. We will follow it up later based on our backlog prioritization.
