### ISSUE TITLE
Sorry, we couldn't get the right information to show the text correctly.

### ISSUE THREAD

**Issue by sajal-24** [microsoft/immersive-reader-sdk#68]
![image](https://user-images.githubusercontent.com/5552121/61621951-7e41fd00-ac91-11e9-9d15-f6f69b38c4df.png)

Getting this error on every w=browser, used Webview option as well but no help. Used default Quickstart C# program from repo. Used susbcription Key from Azure

**Comment by tushararora** [comment]
Getting the same error while running `advanced-nodejs` sample.

This resource is returning 404:
https://learningtools.onenote.com/learningtoolsapi/cognitive/v2.0/GetContentModelForReader

**Comment by metanMSFT** [comment]
Can you folks share a code snippet that reproduces the issue? Thanks. @tushararora @sajal-24

**Comment by spideeee** [comment]
I am also facing this issue when integration Immersive reader with our App based on the instructions given in https://docs.microsoft.com/en-us/azure/cognitive-services/immersive-reader/quickstart.

**Comment by dpaulino** [comment]
Was there ever a solution to this? I'm getting the same problem
![image](https://user-images.githubusercontent.com/7649589/72235620-0ab9e200-3588-11ea-8862-e899e95825bb.png)

**Comment by de-amaro** [comment]
We're also seeing this issue after running through the advanced-nodejs sample.

**Comment by mariuszrokita** [comment]
I also had the same problem when I was creating the service manually. Then I used the Powershell script https://docs.microsoft.com/en-us/azure/cognitive-services/immersive-reader/how-to-create-immersive-reader#set-up-powershell-environment to create another IR service and managed to successfully create it.

**Comment by cloversmith** [comment]
> this still happening

Same for me, having the same issie with OneNote 2021 on my windows 10 machine

I just started using OneNote last week and was exploring its features, I'm getting same error with immersive reader.

**Comment by jeremiahoclark** [comment]
I also have this issue when I deploy to server, but oddly not when I am deploying locally.  
@metanMSFT can you ask the IR team to just open source the source code? Would be great "AI Open Source" news for MSFT. This issue has been ongoing for the last four years 😅 
<img width="707" alt="image" src="https://github.com/microsoft/immersive-reader-sdk/assets/35677370/7d26c455-150f-4454-a6b9-6de18820c40c">

**Comment by parth211prajapati** [comment]
"Happy New Year! 🎉 Still facing the same issue... some things never change, even in 2025! 😅 Here's to hoping for a bug-free year! 🍾"

**Comment by parth211prajapati** [comment]
"Happy New Year! 🎉 Still facing the same issue... some things never change, even in 2025! 😅 Here's to hoping for a bug-free year! 🍾"

![Image](https://github.com/user-attachments/assets/ad9804af-5661-4914-933b-a00b6847f08e)
