### ISSUE TITLE
Publish immersive-reader-sdk on npm

### ISSUE THREAD

**Issue by robinwassen** [Microsoft/immersive-reader-sdk#7]
Any chance that you can publish the built SDK on npm when releasing new versions? It would help for dependency management of the SDK when bundling it into an Electron app.

**Comment by metanMSFT** [comment]
Yes, I will begin looking into that. Stay tuned :)

**Comment by metanMSFT** [comment]
Published as https://www.npmjs.com/package/@microsoft/immersive-reader-sdk
